name: Chess Club Leaderboard Automation

on:
  schedule:
    # Run once daily at midnight
    - cron: "0 0 * * *"
  workflow_dispatch: # manual trigger allowed

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install requests pandas

      - name: Run Chess leaderboard script
        run: |
          echo "Running chess leaderboard script..."
          python chess_leaderboard.py || echo "Script failed!"

      - name: Commit CSVs to repository
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Set remote using token
          git remote set-url origin https://x-access-token:${PAT}@github.com/jcorr92/chess_club_leaderboard.git

          git add leaderboard.csv game_list.csv

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update Chess leaderboard and game list CSVs"
            git push
          fi
